local M = {}

local function style(value, fallback)
  if value == nil then
    return fallback or {}
  end
  return value
end

function M.get(c, opts)
  local transparent = opts.transparent
  local bg = transparent and c.none or c.bg
  local bg_float = transparent and c.none or c.bg_float
  local comments = style(opts.styles.comments)
  local keywords = style(opts.styles.keywords)
  local functions = style(opts.styles.functions)
  local variables = style(opts.styles.variables)

  return {
    Normal = { fg = c.fg, bg = bg },
    NormalNC = { fg = c.fg_dim, bg = bg },
    NormalFloat = { fg = c.fg, bg = bg_float },
    FloatBorder = { fg = c.border, bg = bg_float },
    FloatTitle = { fg = c.cyan, bg = bg_float, bold = true },
    ColorColumn = { bg = c.line },
    Conceal = { fg = c.fg_muted },
    Cursor = { fg = c.bg, bg = c.fg },
    CursorColumn = { bg = c.line },
    CursorLine = { bg = c.line },
    CursorLineNr = { fg = c.yellow, bg = c.line, bold = true },
    Directory = { fg = c.directory },
    EndOfBuffer = { fg = c.bg_dark },
    ErrorMsg = { fg = c.red, bold = true },
    FoldColumn = { fg = c.fg_muted, bg = bg },
    Folded = { fg = c.fg_muted, bg = c.bg_highlight },
    IncSearch = { fg = c.bg, bg = c.orange, bold = true },
    LineNr = { fg = c.fg_muted },
    MatchParen = { fg = c.yellow, bg = c.bg_highlight, bold = true },
    ModeMsg = { fg = c.prompt, bold = true },
    MoreMsg = { fg = c.prompt },
    MsgArea = { fg = c.fg },
    MsgSeparator = { fg = c.border },
    NonText = { fg = c.fg_muted },
    Pmenu = { fg = c.fg, bg = c.bg_float },
    PmenuSbar = { bg = c.bg_highlight },
    PmenuSel = { fg = c.bg, bg = c.cyan, bold = true },
    PmenuThumb = { bg = c.selection },
    Question = { fg = c.prompt },
    QuickFixLine = { fg = c.yellow, bg = c.bg_highlight, bold = true },
    Search = { fg = c.bg, bg = c.yellow },
    SignColumn = { fg = c.fg_muted, bg = bg },
    SpecialKey = { fg = c.fg_muted },
    SpellBad = { sp = c.red, undercurl = true },
    SpellCap = { sp = c.blue, undercurl = true },
    SpellLocal = { sp = c.cyan, undercurl = true },
    SpellRare = { sp = c.purple, undercurl = true },
    StatusLine = { fg = c.fg, bg = c.bg_highlight },
    StatusLineNC = { fg = c.fg_muted, bg = c.line },
    Substitute = { fg = c.bg, bg = c.magenta, bold = true },
    TabLine = { fg = c.fg_muted, bg = c.line },
    TabLineFill = { bg = c.bg_dark },
    TabLineSel = { fg = c.fg, bg = c.bg_highlight, bold = true },
    Title = { fg = c.magenta, bold = true },
    VertSplit = { fg = c.border },
    Visual = { bg = c.bg_visual },
    VisualNOS = { bg = c.bg_visual },
    WarningMsg = { fg = c.yellow, bold = true },
    Whitespace = { fg = c.fg_muted },
    WildMenu = { fg = c.bg, bg = c.prompt },
    WinBar = { fg = c.fg, bg = bg },
    WinBarNC = { fg = c.fg_muted, bg = bg },
    WinSeparator = { fg = c.border },

    Comment = vim.tbl_extend("force", { fg = c.comment }, comments),
    Constant = { fg = c.orange },
    String = { fg = c.string },
    Character = { fg = c.string },
    Number = { fg = c.orange },
    Boolean = { fg = c.orange, bold = true },
    Float = { fg = c.orange },
    Identifier = vim.tbl_extend("force", { fg = c.fg }, variables),
    Function = vim.tbl_extend("force", { fg = c.function_name }, functions),
    Statement = vim.tbl_extend("force", { fg = c.magenta }, keywords),
    Conditional = vim.tbl_extend("force", { fg = c.magenta }, keywords),
    Repeat = vim.tbl_extend("force", { fg = c.magenta }, keywords),
    Label = { fg = c.magenta },
    Operator = { fg = c.cyan },
    Keyword = vim.tbl_extend("force", { fg = c.purple }, keywords),
    Exception = { fg = c.red, bold = true },
    PreProc = { fg = c.yellow },
    Include = { fg = c.cyan },
    Define = { fg = c.purple },
    Macro = { fg = c.purple },
    PreCondit = { fg = c.yellow },
    Type = { fg = c.type },
    StorageClass = { fg = c.type },
    Structure = { fg = c.type },
    Typedef = { fg = c.type },
    Special = { fg = c.cyan },
    SpecialChar = { fg = c.cyan },
    Tag = { fg = c.magenta },
    Delimiter = { fg = c.fg_dim },
    SpecialComment = { fg = c.comment, italic = true, bold = true },
    Debug = { fg = c.red },
    Underlined = { fg = c.blue, underline = true },
    Ignore = { fg = c.fg_muted },
    Error = { fg = c.red, bold = true },
    Todo = { fg = c.bg, bg = c.yellow, bold = true },

    DiagnosticError = { fg = c.red },
    DiagnosticWarn = { fg = c.yellow },
    DiagnosticInfo = { fg = c.blue },
    DiagnosticHint = { fg = c.cyan },
    DiagnosticOk = { fg = c.green },
    DiagnosticUnderlineError = { sp = c.red, undercurl = true },
    DiagnosticUnderlineWarn = { sp = c.yellow, undercurl = true },
    DiagnosticUnderlineInfo = { sp = c.blue, undercurl = true },
    DiagnosticUnderlineHint = { sp = c.cyan, undercurl = true },
    DiagnosticUnderlineOk = { sp = c.green, undercurl = true },
    DiagnosticVirtualTextError = { fg = c.red_dim, bg = c.diff_delete },
    DiagnosticVirtualTextWarn = { fg = c.yellow_dim, bg = "#2f1510" },
    DiagnosticVirtualTextInfo = { fg = c.blue_dim, bg = "#102a45" },
    DiagnosticVirtualTextHint = { fg = c.cyan_dim, bg = "#10393d" },
    DiagnosticVirtualTextOk = { fg = c.green_dim, bg = c.diff_add },
    DiagnosticFloatingError = { fg = c.red },
    DiagnosticFloatingWarn = { fg = c.yellow },
    DiagnosticFloatingInfo = { fg = c.blue },
    DiagnosticFloatingHint = { fg = c.cyan },
    DiagnosticFloatingOk = { fg = c.green },
    DiagnosticSignError = { fg = c.red },
    DiagnosticSignWarn = { fg = c.yellow },
    DiagnosticSignInfo = { fg = c.blue },
    DiagnosticSignHint = { fg = c.cyan },
    DiagnosticSignOk = { fg = c.green },

    DiffAdd = { bg = c.diff_add },
    DiffChange = { bg = c.diff_change },
    DiffDelete = { fg = c.red, bg = c.diff_delete },
    DiffText = { bg = c.diff_text },
    Added = { fg = c.green },
    Changed = { fg = c.blue },
    Removed = { fg = c.red },

    GitSignsAdd = { fg = c.git_add },
    GitSignsChange = { fg = c.git_change },
    GitSignsDelete = { fg = c.git_delete },

    TermCursor = { fg = c.bg, bg = c.fg },
    TermCursorNC = { fg = c.bg, bg = c.fg_muted },
  }
end

return M
